version: '3.1'

volumes:
  pg_selectel:

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=store
    volumes:
      - d:/dev/docker/volumes/postgres/:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
  redis_db:
    image: redis
    restart: always
    volumes:
      - ./volumes/redis/etc/redis.conf:/usr/local/redis/etc/redis.conf
      - ./volumes/redis/data:/data
    command: redis-server /usr/local/redis/etc/redis.conf
    ports:
      - 6379:6379
  filestorage:
    image: filestore
    ports:
      - 80:80